[platformio]
extra_configs = secrets.ini

[env:esp32]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 1000000

lib_deps =
    waspinator/AccelStepper @^1.64
    https://github.com/workloads/scservo.git

[env:endstop_test]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
build_src_filter = -<*> +<../test_scripts/endstop_test.cpp>

lib_deps =
    waspinator/AccelStepper @^1.64

[env:wifi_test]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
build_src_filter = -<*> +<../test_scripts/wifi_test.cpp>
build_flags =
    -DWIFI_SSID=\"${secrets.wifi_ssid}\"
    -DWIFI_PASS=\"${secrets.wifi_pass}\"

lib_deps =
    waspinator/AccelStepper @^1.64
    WiFi @^2.0.0

[env:gripper_test]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
build_src_filter = -<*> +<../test_scripts/gripper_test.cpp>

lib_deps =
    https://github.com/workloads/scservo.git

[env:gripper_raw_test]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
build_src_filter = -<*> +<../test_scripts/gripper_raw_test.cpp>

[env:sts3215_test]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
build_src_filter = -<*> +<../test_scripts/sts3215_test.cpp>

lib_deps =
    https://github.com/workloads/scservo.git