[env:esp32]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 1000000

lib_deps =
    waspinator/AccelStepper @^1.64
    ROBOTIS-GIT/Dynamixel2Arduino @^0.8.1

[env:endstop_test]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
build_src_filter = -<*> +<../test_scripts/endstop_test.cpp>

lib_deps =
    waspinator/AccelStepper @^1.64
